
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Aug 21 01:53:55 CEST 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 23;
  public static final int CONST = 16;
  public static final int NUMCONSTANT = 42;
  public static final int SEMI = 33;
  public static final int CONTINUE = 15;
  public static final int MINUS = 18;
  public static final int RCBRACKET = 41;
  public static final int AND = 26;
  public static final int LT = 22;
  public static final int OR = 27;
  public static final int COMMA = 34;
  public static final int CLASS = 4;
  public static final int INC = 31;
  public static final int DIV = 20;
  public static final int BOOLCONSTANT = 43;
  public static final int PLUS = 17;
  public static final int ASSIGN = 30;
  public static final int IF = 6;
  public static final int RRBRACKET = 37;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RSBRACKET = 39;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 19;
  public static final int CHARCONSTANT = 44;
  public static final int MOD = 21;
  public static final int NEQ = 29;
  public static final int IDENT = 45;
  public static final int BREAK = 3;
  public static final int VOID = 11;
  public static final int EQ = 28;
  public static final int GTE = 25;
  public static final int ELSE = 5;
  public static final int LCBRACKET = 40;
  public static final int READ = 9;
  public static final int WHILE = 13;
  public static final int EXTENDS = 14;
  public static final int LRBRACKET = 36;
  public static final int DEC = 32;
  public static final int GT = 24;
  public static final int LSBRACKET = 38;
  public static final int PRINT = 8;
  public static final int DO = 12;
}

